language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"

before_install:
  - sudo apt-get update -qq

install:
  - pip install coveralls

script:
  - coverage run --source=djcelery_ses setup.py test

after_success:
  - coveralls
